# Change these first
owner: ccmbioinfo
repo: status-genomics4rd

sites:
  - name: Stager (frontend)
    url: https://stager.genomics4rd.ca
  - name: Stager (backend)
    url: https://stager.genomics4rd.ca/api
  - name: MinIO
    url: http://minio.genomics4rd.ca/minio/health/live

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.genomics4rd.ca
  baseUrl: /status-genomics4rd
  logoUrl: https://images.squarespace-cdn.com/content/v1/6168401f7acb581581c8313a/94a1de18-da7e-48bb-8095-31b33eb03ebf/genomics4rd-logo-web.png
  name: Genomics4RD status
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
